# -*- coding: utf-8 -*-
"""assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3pT1KC_4VUQfs3XYTiW2tVCGU1okpiz

Question 1
 plot a line plot between a and b:
a=np.arange(40,50)
b=np.arange(50,60)
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
from numpy.random import randn, randint, uniform, sample

import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

a=np.arange(40,50)
b=np.arange(50,60)

plt.plot(a,b,'go--', linewidth=1, markersize=5)
plt.title('Line Plot between a and b')
plt.xlabel('a')
plt.ylabel('b')

"""##Question 2
Plot a line plot showing the sales trend in company 1 and 2:

days = [1,2,3,4,5,6,7] #days of d week

sales_1 = [160,150,140,145,175,165,180] #sales of company1

sales_2 = [70,90,160,150,140,145,175]  #sales of company2


"""

days = [1,2,3,4,5,6,7] #days of d week
sales_1 = [160,150,140,145,175,165,180] #sales of company1
sales_2 = [70,90,160,150,140,145,175]  #sales of company2
plt.title("sales trends of company 1 qand 2")
plt.plot(days,sales_1,'b*--',color='r',label='company 1 sales')
plt.plot(days,sales_2,'b*--',color='g',label='company 2 sales')
plt.xlabel=("days of the week")
plt.ylabel("company sales")
plt.legend(loc='lower right')

"""##Question 3
 Create a 3 by 3 subplots:
multiple plots
x = [1,2,3,4]
y1 = [4,3,2,1]
y2 = [10,20,30,40]
y3 = [40,30,20,10]
y4 = [1,2,1,2]
y5 = [40,70,90,70]

"""

x = [1,2,3,4]
y1 = [4,3,2,1]
y2 = [10,20,30,40]
y3 = [40,30,20,10]
y4 = [1,2,1,2]
y5 = [40,70,90,70]

plt.suptitle('subplots:',fontsize=12)

plt.subplot(3,3,1)
plt.plot(x,y1,'r-')
plt.ylabel('y1')

plt.subplot(3,3,2)
plt.plot(x,y2,'y-')
plt.ylabel('y2')

plt.subplot(3,3,3)
plt.plot(x,y3,'r*-')
plt.ylabel('y3')

plt.subplot(3,3,4)
plt.plot(x,y4,'g*-')
plt.ylabel('y4')

plt.subplot(3,3,5)
plt.plot(x,y5,'r-')
plt.ylabel('y5')